
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CMD.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Patient_Symptom
{

    public int Id { get; set; }

    public int Symptom_ID { get; set; }

    public string Symptom_Name { get; set; }

    public string Reading { get; set; }

    public int symp_Doctor_ID { get; set; }

    public int syom_Patient_ID { get; set; }



    public virtual Doctor Doctor { get; set; }

    public virtual Patient Patient { get; set; }

    public virtual Patient Patient1 { get; set; }

    public virtual Symptom Symptom { get; set; }

}

}
