
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CMD.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Patient
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Patient()
    {

        this.ActiveIssues = new HashSet<ActiveIssue>();

        this.Appointments = new HashSet<Appointment>();

        this.MedicalIssues = new HashSet<MedicalIssue>();

        this.Patient_Symptom = new HashSet<Patient_Symptom>();

        this.Patient_Symptom1 = new HashSet<Patient_Symptom>();

        this.Recommendations = new HashSet<Recommendation>();

        this.Vitals = new HashSet<Vital>();

        this.Prescriptions = new HashSet<Prescription>();

    }


    public int Patient_Id { get; set; }

    public string PatientName { get; set; }

    public string Gender { get; set; }

    public int Age { get; set; }

    public long PhoneNumber { get; set; }

    public string Email { get; set; }

    public System.DateTime DOB { get; set; }

    public string BloodGroup { get; set; }

    public string Password { get; set; }

    public int Height { get; set; }

    public string Allergies { get; set; }

    public Nullable<System.DateTime> Reg_Date { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ActiveIssue> ActiveIssues { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Appointment> Appointments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MedicalIssue> MedicalIssues { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Patient_Symptom> Patient_Symptom { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Patient_Symptom> Patient_Symptom1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Recommendation> Recommendations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Vital> Vitals { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Prescription> Prescriptions { get; set; }

}

}
