
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CMD.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Prescription
{

    public int Prescription_ID { get; set; }

    public int pres_Appointment_ID { get; set; }

    public string Medicine_Name { get; set; }

    public string Medicine_Duration { get; set; }

    public string Time_Of_Day { get; set; }

    public string Medicine_Cycle { get; set; }

    public string Additional_Comments { get; set; }

    public decimal Price { get; set; }

    public int pres_Patient_ID { get; set; }

    public string SymptomName { get; set; }

    public System.DateTime Date { get; set; }



    public virtual Appointment Appointment { get; set; }

    public virtual Patient Patient { get; set; }

}

}
