
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CMD.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Vital
{

    public int VitalID { get; set; }

    public int BloodPressure { get; set; }

    public decimal Temperature { get; set; }

    public string DiabaetesReading { get; set; }

    public string RespirationReadings { get; set; }

    public int Patient_ID { get; set; }



    public virtual Patient Patient { get; set; }

}

}
